server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo1
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: bek96
          client-secret: q1q2q3q4q5